import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../app_store.dart'; import '../dialogs.dart'; import '../theme.dart';

class ScannerPage extends StatefulWidget { const ScannerPage({required this.store, required this.onSaved, super.key}); final AppStore store; final VoidCallback onSaved; @override State<ScannerPage> createState() => _ScannerPageState(); }
class _ScannerPageState extends State<ScannerPage> { XFile? image; bool working = false;
  Future<void> pick(ImageSource source) async { final selected = await ImagePicker().pickImage(source: source, imageQuality: 82, maxWidth: 1800); if (selected == null) return; setState(() { image = selected; working = true; }); await Future<void>.delayed(const Duration(milliseconds: 650)); if (!mounted) return; setState(() => working = false); await editExpense(context, widget.store, receiptPath: selected.path); if (mounted && widget.store.expenses.any((e)=>e.receiptPath == selected.path)) widget.onSaved(); }
  @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20,22,20,40), children: [const GradientTitle('Сканер чека'), const SizedBox(height: 8), const Text('Оберіть фото чека. Дані залишаються на пристрої — суму та категорію ви підтверджуєте вручну.', style: TextStyle(color: Colors.white60, height: 1.4)), const SizedBox(height: 24), AnimatedContainer(duration: const Duration(milliseconds: 300), height: 300, decoration: BoxDecoration(borderRadius: BorderRadius.circular(28), color: panel, border: Border.all(color: image == null ? const Color(0xFF33333A) : green)), clipBehavior: Clip.antiAlias, child: image == null ? const Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(Icons.receipt_long_outlined, size: 72, color: purple), SizedBox(height: 14), Text('Фото чека з’явиться тут', style: TextStyle(fontWeight: FontWeight.bold))]) : Stack(fit: StackFit.expand, children: [Image.file(File(image!.path), fit: BoxFit.cover), if (working) Container(color: Colors.black54, child: const Center(child: CircularProgressIndicator()))])), const SizedBox(height: 18), FilledButton.icon(onPressed: working ? null : ()=>pick(ImageSource.camera), icon: const Icon(Icons.camera_alt), label: const Padding(padding: EdgeInsets.all(15), child: Text('Зробити фото'))), const SizedBox(height: 10), OutlinedButton.icon(onPressed: working ? null : ()=>pick(ImageSource.gallery), icon: const Icon(Icons.photo_library_outlined), label: const Padding(padding: EdgeInsets.all(15), child: Text('Обрати з галереї'))), const SizedBox(height: 18), const Row(children: [Icon(Icons.lock_outline, color: green, size: 18), SizedBox(width: 8), Expanded(child: Text('Без хмарного OCR та без API-ключів', style: TextStyle(color: Colors.white54)))])]); }
