import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import 'app_store.dart';
import 'models.dart';

Future<void> editTask(BuildContext context, AppStore store, [TodoItem? item]) async {
  final title = TextEditingController(text: item?.title); final note = TextEditingController(text: item?.note);
  var category = item?.category ?? 'Особисте'; var priority = item?.priority ?? TaskPriority.medium; var deadline = item?.deadline;
  await showDialog<void>(context: context, builder: (context) => StatefulBuilder(builder: (context, setState) => AlertDialog(title: Text(item == null ? 'Нове завдання' : 'Редагувати завдання'), content: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, children: [
    TextField(controller: title, autofocus: true, decoration: const InputDecoration(labelText: 'Назва')), const SizedBox(height: 12), TextField(controller: note, maxLines: 3, decoration: const InputDecoration(labelText: 'Нотатка')), const SizedBox(height: 12),
    DropdownButtonFormField(initialValue: category, decoration: const InputDecoration(labelText: 'Категорія'), items: ['Особисте','Робота','Дім','Здоров’я','Покупки'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(), onChanged: (v) => setState(() => category = v!)), const SizedBox(height: 12),
    DropdownButtonFormField(initialValue: priority, decoration: const InputDecoration(labelText: 'Пріоритет'), items: const [DropdownMenuItem(value: TaskPriority.low, child: Text('Низький')), DropdownMenuItem(value: TaskPriority.medium, child: Text('Середній')), DropdownMenuItem(value: TaskPriority.high, child: Text('Високий'))], onChanged: (v) => setState(() => priority = v!)), const SizedBox(height: 12),
    ListTile(contentPadding: EdgeInsets.zero, title: Text(deadline == null ? 'Без дедлайну' : DateFormat('dd.MM.yyyy').format(deadline!)), trailing: const Icon(Icons.calendar_month), onTap: () async { final d = await showDatePicker(context: context, firstDate: DateTime.now().subtract(const Duration(days: 365)), lastDate: DateTime.now().add(const Duration(days: 3650)), initialDate: deadline ?? DateTime.now()); if (d != null) setState(() => deadline = d); }),
  ])), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Скасувати')), FilledButton(onPressed: () { if (title.text.trim().isEmpty) return; if (item == null) { store.tasks.add(TodoItem(id: store.id(), title: title.text.trim(), note: note.text.trim(), category: category, priority: priority, deadline: deadline)); } else { item..title = title.text.trim()..note = note.text.trim()..category = category..priority = priority..deadline = deadline; } store.changed(); Navigator.pop(context); }, child: const Text('Зберегти'))])));
}

Future<void> editExpense(BuildContext context, AppStore store, {Expense? item, String? receiptPath}) async {
  final title = TextEditingController(text: item?.title ?? 'Покупка'); final amount = TextEditingController(text: item?.amount.toStringAsFixed(2)); var category = item?.category ?? 'Продукти';
  await showDialog<void>(context: context, builder: (context) => StatefulBuilder(builder: (context, setState) => AlertDialog(title: Text(item == null ? 'Підтвердьте витрату' : 'Редагувати витрату'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: title, decoration: const InputDecoration(labelText: 'Опис')), const SizedBox(height: 12), TextField(controller: amount, keyboardType: const TextInputType.numberWithOptions(decimal: true), decoration: const InputDecoration(labelText: 'Сума, ₴')), const SizedBox(height: 12), DropdownButtonFormField(initialValue: category, decoration: const InputDecoration(labelText: 'Категорія'), items: ['Продукти','Транспорт','Дім','Здоров’я','Розваги','Інше'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(), onChanged: (v) => setState(() => category = v!))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Скасувати')), FilledButton(onPressed: () { final parsed = double.tryParse(amount.text.replaceAll(',', '.')); if (title.text.trim().isEmpty || parsed == null || parsed <= 0) return; if (item == null) { store.expenses.add(Expense(id: store.id(), title: title.text.trim(), amount: parsed, category: category, date: DateTime.now(), receiptPath: receiptPath)); } else { item..title = title.text.trim()..amount = parsed..category = category; } store.changed(); Navigator.pop(context); }, child: const Text('Зберегти'))])));
}

Future<void> editFood(BuildContext context, AppStore store, [FoodEntry? item]) async {
  final values = [TextEditingController(text: item?.name), TextEditingController(text: item?.calories.toString()), TextEditingController(text: item?.protein.toString()), TextEditingController(text: item?.fat.toString()), TextEditingController(text: item?.carbs.toString())];
  await showDialog<void>(context: context, builder: (context) => AlertDialog(title: Text(item == null ? 'Додати продукт' : 'Редагувати продукт'), content: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, children: List.generate(values.length, (i) => Padding(padding: const EdgeInsets.only(bottom: 10), child: TextField(controller: values[i], keyboardType: i == 0 ? TextInputType.text : const TextInputType.numberWithOptions(decimal: true), decoration: InputDecoration(labelText: ['Назва','Калорії, ккал','Білки, г','Жири, г','Вуглеводи, г'][i])))))), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Скасувати')), FilledButton(onPressed: () { double n(int i) => double.tryParse(values[i].text.replaceAll(',', '.')) ?? 0; if (values[0].text.trim().isEmpty) return; if (item == null) { store.foods.add(FoodEntry(id: store.id(), name: values[0].text.trim(), calories: n(1), protein: n(2), fat: n(3), carbs: n(4), date: DateTime.now())); } else { item..name = values[0].text.trim()..calories = n(1)..protein = n(2)..fat = n(3)..carbs = n(4); } store.changed(); Navigator.pop(context); }, child: const Text('Зберегти'))]));
}
